'use client';

import {useQuery} from '@tanstack/react-query';
import {ArrowRight,Building2,CalendarDays,CheckCircle2,ClipboardCheck,ExternalLink,Flag,Plus,ShieldCheck,Users} from 'lucide-react';
import Link from 'next/link';
import {useState} from 'react';

import {api,post,pretty} from '@/lib/api';
import {WardGoals} from './ward-goals';

type Props={me:any;busy:boolean;act:(fn:()=>Promise<any>,message?:string)=>Promise<any>};

export function AdminScreen({me,busy,act}:Props){
 const [tab,setTab]=useState('escalations');
 const moderation=useQuery({queryKey:['admin-moderation'],queryFn:()=>api('/admin/moderation/cases'),enabled:['moderator','admin'].includes(me?.role)});
 const escalations=useQuery({queryKey:['admin-escalations'],queryFn:()=>api('/admin/escalation-cases'),enabled:['moderator','admin'].includes(me?.role)});
 const resolutions=useQuery({queryKey:['admin-resolutions'],queryFn:()=>api('/admin/resolutions'),enabled:['moderator','admin'].includes(me?.role)});
 const appeals=useQuery({queryKey:['admin-appeals'],queryFn:()=>api('/admin/appeals'),enabled:['moderator','admin'].includes(me?.role)});
 const actions=useQuery({queryKey:['admin-actions'],queryFn:()=>api('/civic-actions'),enabled:me?.role==='admin'});
 const groups=useQuery({queryKey:['admin-groups'],queryFn:()=>api('/admin/community-groups'),enabled:me?.role==='admin'});
 const authorities=useQuery({queryKey:['admin-authorities'],queryFn:()=>api('/admin/authorities'),enabled:me?.role==='admin'});
 const officers=useQuery({queryKey:['admin-officers'],queryFn:()=>api('/admin/officers'),enabled:me?.role==='admin'});
 const geography=useQuery({queryKey:['geography'],queryFn:()=>api('/geography'),enabled:me?.role==='admin'});
 const categories=useQuery({queryKey:['categories'],queryFn:()=>api('/categories'),enabled:me?.role==='admin'});
 if(me&&!['moderator','admin'].includes(me.role))return <div className="state"><ShieldCheck/><h2>Reviewer access required</h2><p>Use a moderator or admin identity to open this audited workspace.</p><Link className="button dark" href="/profile">Open Profile</Link></div>;
 const tabs=[['escalations','Escalations'],['reports','Reports'],['resolutions','Resolutions'],['appeals','Appeals'],...(me?.role==='admin'?[['actions','Actions'],['ward-goals','Ward Goals'],['ownership','Ownership'],['groups','Groups']]:[])];
 return <><header className="page-title"><span className="kicker">AUDITED CIVIC REVIEW</span><h1>Trust workspace</h1><p>Review community evidence, record external handoffs, and keep official status sourced.</p></header><div className="hub-tabs admin-tabs" role="tablist">{tabs.map(([value,label])=><button role="tab" aria-selected={tab===value} className={tab===value?'selected':''} key={value} onClick={()=>setTab(value)}>{label}</button>)}</div>
 {tab==='escalations'&&<div className="review-stack">{escalations.data?.items?.map((item:any)=><EscalationCard key={item.id} item={item} busy={busy} act={act}/>) }{!escalations.isPending&&!escalations.data?.items?.length&&<ClearQueue/>}</div>}
 {tab==='reports'&&<div className="review-stack">{moderation.data?.items?.map((item:any)=><ModerationCard item={item} busy={busy} act={act} key={item.id}/>)}{!moderation.isPending&&!moderation.data?.items?.length&&<ClearQueue/>}</div>}
 {tab==='resolutions'&&<DecisionList items={resolutions.data?.items||[]} kind="resolutions" busy={busy} act={act}/>} 
 {tab==='appeals'&&<DecisionList items={appeals.data?.items||[]} kind="appeals" busy={busy} act={act}/>} 
 {tab==='actions'&&<ActionAdmin items={actions.data?.items||[]} busy={busy} act={act}/>} 
 {tab==='ward-goals'&&<WardGoals admin/>}
 {tab==='ownership'&&<OwnershipAdmin authorities={authorities.data?.items||[]} officers={officers.data?.items||[]} geography={geography.data} categories={categories.data||[]} busy={busy} act={act}/>} 
 {tab==='groups'&&<GroupAdmin items={groups.data?.items||[]} busy={busy} act={act}/>} 
 </>;
}

function ClearQueue(){return <div className="state"><CheckCircle2/><h2>Queue clear</h2><p>New cases will appear here when they need a human decision.</p></div>}

function ModerationCard({item,busy,act}:any){const [reason,setReason]=useState('Reviewed against the CivicQuest community rules.');return <article className="review-card"><div className="review-card-head"><span className="status-pill review">Priority {item.priority}</span><Flag/></div><h2>{pretty(item.kind)}</h2>{item.details?.comment&&<blockquote>{item.details.comment}</blockquote>}<p>{item.details?.reason||item.details?.flags?.map(pretty).join(', ')||'Evidence is ready for review.'}</p>{item.kind==='comment_abuse'?<><label>Decision note<textarea value={reason} onChange={event=>setReason(event.target.value)} rows={2}/></label><div className="button-row"><button className="button dark" disabled={busy||reason.length<5} onClick={()=>act(()=>post(`/admin/moderation/cases/${item.id}/comment-decision`,{decision:'remove',reason}),'Comment removed')}>Remove comment</button><button className="button outline" disabled={busy||reason.length<5} onClick={()=>act(()=>post(`/admin/moderation/cases/${item.id}/comment-decision`,{decision:'keep',reason}),'Comment kept')}>Keep comment</button></div></>:<Link className="button dark full" href={`/reports/${item.report_id}`}>Review report <ArrowRight/></Link>}</article>}

function EscalationCard({item,busy,act}:any){
 const [reason,setReason]=useState('Community threshold and evidence reviewed.');const [source,setSource]=useState('BMC complaint portal');const [sourceUrl,setSourceUrl]=useState('https://portal.mcgm.gov.in/');const [officialId,setOfficialId]=useState('');const [status,setStatus]=useState('');
 return <article className="review-card"><div className="review-card-head"><span className={`status-pill ${item.state}`}>{pretty(item.state)}</span><ClipboardCheck/></div><span className="kicker">{item.report_code||'CIVICQUEST REPORT'} · {item.threshold} SEEN</span><h2>{item.report_title}</h2><Link className="text-button" href={`/reports/${item.report_id}`}>Open evidence <ExternalLink size={15}/></Link>{item.state==='review'&&<><label>Review note<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={2}/></label><div className="button-row"><button disabled={busy||reason.length<5} className="button dark" onClick={()=>act(()=>post(`/admin/escalation-cases/${item.id}/decision`,{approved:true,reason}),'Escalation approved for handoff')}>Approve</button><button disabled={busy||reason.length<5} className="button outline" onClick={()=>act(()=>post(`/admin/escalation-cases/${item.id}/decision`,{approved:false,reason}),'Escalation declined')}>Decline</button></div></>}{item.state==='approved'&&<><p className="notice">Approval does not contact BMC. Record the real external handoff below.</p><label>Official channel<input value={source} onChange={e=>setSource(e.target.value)}/></label><label>Official source URL<input type="url" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/></label><label>Official complaint ID <span className="optional">Optional until supplied</span><input value={officialId} onChange={e=>setOfficialId(e.target.value)}/></label><button className="button dark full" disabled={busy||source.length<2} onClick={()=>act(()=>post(`/admin/escalation-cases/${item.id}/handoff`,{source_name:source,source_url:sourceUrl,official_id:officialId||null,receipt_key:null}),'External handoff recorded')}>Record handoff</button></>}{item.complaint&&<><div className="official-record"><strong>{item.complaint.official_id||'Official complaint pending'}</strong><span>{item.complaint.source_name}</span>{item.complaint.source_url&&<a href={item.complaint.source_url} rel="noreferrer" target="_blank">Open source <ExternalLink size={13}/></a>}<small>Handed off {new Date(item.complaint.handed_off_at).toLocaleString('en-IN')}</small></div><label>New sourced status<input value={status} onChange={e=>setStatus(e.target.value)} placeholder="For example: Assigned for inspection"/></label><button className="button outline full" disabled={busy||status.length<2} onClick={()=>act(()=>post(`/admin/complaints/${item.complaint.id}/status`,{status,occurred_at:new Date().toISOString(),source_note:`Checked through ${item.complaint.source_name}`}), 'Official status recorded')}>Add status update</button></>}</article>;
}

function DecisionList({items,kind,busy,act}:any){const [reason,setReason]=useState('Evidence reviewed against the CivicQuest rules.');if(!items.length)return <ClearQueue/>;return <div className="review-stack">{items.map((item:any)=><article className="review-card" key={item.id}><span className="kicker">{kind==='appeals'?pretty(item.target_type):'RESOLUTION PROOF'}</span><h2>{item.description||item.reason}</h2>{item.media&&<div className="proof-images">{item.media.map((media:any)=><img src={media.url} alt="Submitted resolution proof" key={media.id}/>)}</div>}<label>Decision note<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={2}/></label><div className="button-row">{[true,false].map(approved=><button className={approved?'button dark':'button outline'} disabled={busy} key={String(approved)} onClick={()=>act(()=>post(`/admin/${kind}/${item.id}/decision`,{approved,reason}),`${pretty(kind)} reviewed`)}>{approved?'Approve':'Reject'}</button>)}</div></article>)}</div>}

function ActionAdmin({items,busy,act}:any){const [open,setOpen]=useState(false);async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await act(()=>post('/admin/actions',{title:f.get('title'),description:f.get('description'),organizer:f.get('organizer'),location_name:f.get('location_name'),lat:Number(f.get('lat')),lng:Number(f.get('lng')),starts_at:new Date(String(f.get('starts_at'))).toISOString(),ends_at:new Date(String(f.get('ends_at'))).toISOString(),capacity:Number(f.get('capacity')),status:'published'},crypto.randomUUID()),'Civic Action published');setOpen(false)}return <div className="review-stack"><button className="button dark full" onClick={()=>setOpen(!open)}><Plus/>Create Civic Action</button>{open&&<form className="review-card" onSubmit={create}><h2>New Action</h2>{[['title','Title'],['organizer','Organizer'],['location_name','Location']].map(([name,label])=><label key={name}>{label}<input name={name} minLength={2} required/></label>)}<label>Description<textarea name="description" minLength={5} required/></label><div className="two-fields"><label>Latitude<input name="lat" type="number" step="any" defaultValue="19.076" required/></label><label>Longitude<input name="lng" type="number" step="any" defaultValue="72.8777" required/></label></div><div className="two-fields"><label>Starts<input name="starts_at" type="datetime-local" required/></label><label>Ends<input name="ends_at" type="datetime-local" required/></label></div><label>Capacity<input name="capacity" type="number" min="1" defaultValue="50" required/></label><button className="button dark full" disabled={busy}>Publish Action</button></form>}{items.map((item:any)=><ActionEditor item={item} busy={busy} act={act} key={item.id}/>)}</div>}

function ActionEditor({item,busy,act}:any){const [editing,setEditing]=useState(false);const payload=(status=item.status)=>({title:item.title,description:item.description,organizer:item.organizer,location_name:item.location_name,lat:item.lat,lng:item.lng,starts_at:item.starts_at,ends_at:item.ends_at,capacity:item.capacity,status});return <article className="review-card"><div className="review-card-head"><span className={`status-pill ${item.status}`}>{pretty(item.status)}</span><CalendarDays/></div><h2>{item.title}</h2><p><Users size={13}/> {item.participants} of {item.capacity} joined · {item.location_name}</p><div className="button-row"><Link className="button outline" href={`/actions/${item.id}`}>Open</Link><button className="button outline" onClick={()=>setEditing(!editing)}>Edit</button>{item.status!=='cancelled'&&<button className="button outline" disabled={busy} onClick={()=>act(()=>api(`/admin/actions/${item.id}`,{method:'PATCH',body:JSON.stringify(payload('cancelled'))}),'Action cancelled')}>Cancel</button>}</div>{editing&&<form onSubmit={event=>{event.preventDefault();const f=new FormData(event.currentTarget);act(()=>api(`/admin/actions/${item.id}`,{method:'PATCH',body:JSON.stringify({...payload(),title:f.get('title'),capacity:Number(f.get('capacity'))})}),'Action updated');setEditing(false)}}><label>Title<input name="title" defaultValue={item.title} required/></label><label>Capacity<input name="capacity" type="number" min={item.participants} defaultValue={item.capacity} required/></label><button className="button dark fu