'use client';

import {useQuery} from '@tanstack/react-query';
import {ArrowLeft,ArrowRight,BarChart3,Building2,Download,ExternalLink,Flag,Mail,MapPin,MessageCircle,Phone,Share2,ShieldCheck} from 'lucide-react';
import Link from 'next/link';
import {useState} from 'react';
import {api,post,pretty} from '@/lib/api';
import {WardGoals} from './ward-goals';

type Props={id:string;me:any;busy:boolean;notify:(message:string)=>void;act:(fn:()=>Promise<any>,message?:string)=>Promise<any>};

export function AreaDetailScreen({id,me,busy,notify,act}:Props){const area=useQuery({queryKey:['area',id],queryFn:()=>api(`/areas/${id}`)});const officers=useQuery({queryKey:['officers',id],queryFn:()=>api(`/officers?area_id=${encodeURIComponent(id)}`)});const authorities=useQuery({queryKey:['authorities',id],queryFn:()=>api(`/authorities?area_id=${encodeURIComponent(id)}`)});const [card,setCard]=useState<string>();if(area.isPending)return <div className="state"><MapPin/><p>Opening this civic area…</p></div>;if(area.isError)return <div className="error">This area is unavailable.</div>;const item=area.data,stats=item.statistics;async function shareWard(){if(me?.identity_type!=='registered'||!me?.handle)return notify('Create a linked public profile before sharing.');const made=await act(()=>post('/share-cards',{kind:'ward',area_id:id},crypto.randomUUID()),'Preparing Help Fix My Ward');if(!made)return;for(let attempt=0;attempt<15;attempt++){await new Promise(resolve=>setTimeout(resolve,700));const state=await api(`/share-cards/${made.id}`);if(state.state==='ready'){setCard(state.url);return}}notify('The ward card is still processing.')}
 return <><Link className="back-link" href="/"><ArrowLeft/>Back to Explore</Link><header className="area-mobile-head"><span className="kicker">{pretty(item.area_type)} · {item.code}</span><h1>{item.name}</h1><p>Factual public reports and sourced accountability context.</p>{item.synthetic&&<span className="demo-area"><ShieldCheck/>Illustrative local demo geography</span>}</header><div className="area-mobile-stats"><span><strong>{stats.active}</strong>Active</span><span><strong>{stats.resolved}</strong>Resolved</span><span><strong>{stats.total_reports}</strong>Total</span><span><strong>{stats.resolution_rate===null?'—':`${(stats.resolution_rate*100).toFixed(0)}%`}</strong>Resolution</span></div><p className="field-note">{stats.counting_method}. {stats.boundary_note}</p>
 {item.area_type==='ward'&&<section className="ward-share-panel"><Share2/><div><span className="kicker">SHARED WARD GOAL</span><h2>Help Fix My Ward</h2><p>Share verified outcomes for {item.name}. Personal XP is excluded.</p></div><button className="button dark full" disabled={busy} onClick={shareWard}>Create ward card</button>{card&&<><img className="share-preview" src={card} alt={`Help Fix ${item.name} card`}/><a className="button outline full" href={card} download="civicquest-ward.png"><Download/>Download</a></>}</section>}
 {item.area_type==='ward'&&<WardGoals areaId={id}/>}<section className="report-section"><h2><BarChart3/>Issue breakdown</h2>{Object.entries(stats.by_category).map(([category,count])=><div className="area-category" key={category}><span>{pretty(category)}</span><strong>{String(count)}</strong></div>)}{!Object.keys(stats.by_category).length&&<p>No eligible public reports in this area.</p>}</section>
 <section className="report-section"><h2><Building2/>Operational ownership</h2><p>Responsibility is shown by issue family only when a reviewed, current source supports it.</p>{authorities.data?.items?.map((owner:any)=><article className="officer-card" key={owner.id}><span className="kicker">{pretty(owner.category_family)}</span><h3>{owner.name}</h3><strong>{owner.department}</strong><p>Effective from {new Date(`${owner.effective_from}T00:00:00`).toLocaleDateString('en-IN')}{owner.effective_to?` to ${new Date(`${owner.effective_to}T00:00:00`).toLocaleDateString('en-IN')}`:''}.</p><small><a href={owner.source_url} target="_blank" rel="noreferrer">View official source</a></small></article>)}{!authorities.isPending&&!authorities.data?.items?.length&&<p>Owner not confirmed for any issue family.</p>}</section><section className="report-section"><h2><Phone/>Ward contacts</h2><p>Contacts appear only from active, reviewed records. Elected representatives are shown separately below.</p>{officers.data?.items?.map((officer:any)=><article className="officer-card" key={officer.id}><span className="kicker">{officer.department}</span><h3>{officer.name}</h3><strong>{officer.title}</strong><p>{officer.reason}</p><div className="officer-actions">{officer.contacts.phone&&<a href={contactHref(officer.contacts.phone,'tel')}><Phone/>Call</a>}{officer.contacts.whatsapp&&<a href={contactHref(officer.contacts.whatsapp,'https')} target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp</a>}{officer.contacts.email&&<a href={contactHref(officer.contacts.email,'mailto')}><Mail/>Email</a>}{officer.contacts.official&&<a href={officer.contacts.official} target="_blank" rel="noreferrer"><ExternalLink/>Official</a>}</div><small>Source verified {new Date(officer.verified_at).toLocaleDateString('en-IN')} · <a href={officer.source_url} target="_blank" rel="noreferrer">View source</a></small></article>)}{!officers.isPending&&!officers.data?.items?.length&&<p>No current reviewed ward contact is available.</p>}</section>
 <section className="report-section"><h2><Flag/>Recent reports</h2>{item.reports.map((report:any)=><Link className="area-report-row" href={`/i/${report.public_code}`} key={report.id}><span className={`severity-pill ${report.severity}`}>{report.severity}</span><span><strong>{report.title}</strong><small>{report.public_code} · {pretty(report.status)}</small></span><ArrowRight/></Link>)}{!item.reports.length&&<p>No recent public reports.</p>}</section>
 <section className="report-section"><h2>{item.area_type==='ward'?'Constituency context':'Overlapping wards'}</h2><p>{item.context_note}</p>{[...(item.constituencies||[]),...(item.wards||[])].map((related:any)=><Link className="representative-row" href={`/areas/${related.id}`} key={related.id}><span><strong>{related.name}</strong><small>{pretty(related.area_type)}</small></span><ArrowRight/></Link>)}{!(item.constituencies?.length||item.wards?.length)&&<p>No reviewed overlapping geography is available.</p>}</section><section className="report-section"><h2>Elected representative context</h2><p>Elected representatives provide factual constituency context and are not automatically the operational owner.</p>{item.representatives.map((person:any)=><a className="representative-row elected-row" href={person.source_url} target="_blank" rel="noreferrer" key={`${person.role}-${person.name}`}>{person.photo_url?<img src={person.photo_url} alt=""/>:<span className="rep-initials" aria-hidden="true">{person.name.split(' ').slice(0,2).map((part:string)=>part[0]).join('')}</span>}<span><strong>{person.name}</strong><small>{person.party||'Party not recorded'} · {person.role}</small><small>{person.source_name||'Reviewed term record'}{person.fetched_at?` · checked ${new Date(person.fetched_at).toLocaleDateString('en-IN')}`:''}</small></span><ExternalLink/></a>)}{!item.representatives.length&&<p>No current reviewed representative record.</p>}</section><section className="area-provenance"><ShieldCheck/><div><strong>{item.provenance.dataset} · version {item.provenance.version}</strong><p>{item.provenance.license} · {item.provenance.reviewed?'reviewed':'awaiting review'}</p><a href={item.provenance.source_url} target="_blank" rel="noreferrer">View geographic source</a></div></section></>;
}

function contactHref(value:string,scheme:'tel'|'mailto'|'https'){if(value.includes(':'))return value;if(scheme==='https')return `https://wa.me/${value.replace(/\D/g,'')}`;return `${scheme}:${value}`}
