'use client';

import {Camera, CircleStop, Clock, LocateFixed, Lock, ShieldCheck, Video, X} from 'lucide-react';
import Link from 'next/link';
import {useEffect, useRef, useState} from 'react';
import {api, csrf, locate, post} from '@/lib/api';

type Props={me:any;notify:(message:string)=>void};
type Capture={file:File;url:string;kind:'photo'|'video'};

export function CatchCaptureScreen({me,notify}:Props){
 const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const recorder=useRef<MediaRecorder|null>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [session,setSession]=useState<any>();const [captured,setCaptured]=useState<Capture|null>(null);const [mode,setMode]=useState<'photo'|'video'>('photo');const [recording,setRecording]=useState(false);const [error,setError]=useState('');const [description,setDescription]=useState('');const [address,setAddress]=useState('Mumbai');const [category,setCategory]=useState('littering');const [busy,setBusy]=useState(false);const [result,setResult]=useState<any>();
 useEffect(()=>()=>{stream.current?.getTracks().forEach(track=>track.stop());if(timer.current)clearTimeout(timer.current);if(captured)URL.revokeObjectURL(captured.url);},[captured]);
 async function start(){setError('');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Live camera capture is not supported by this browser.');const position=await locate();const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:mode==='video'});stream.current=media;if(video.current)video.current.srcObject=media;setSession(await post('/catches/capture-sessions',position));}catch(caught:any){setError(`${caught.message} Allow camera and precise location in browser settings, then retry.`)}}
 function keep(file:File,kind:'photo'|'video'){setCaptured(old=>{if(old)URL.revokeObjectURL(old.url);return{file,url:URL.createObjectURL(file),kind}})}
 async function takePhoto(){if(!video.current)return;const canvas=document.createElement('canvas');canvas.width=video.current.videoWidth;canvas.height=video.current.videoHeight;canvas.getContext('2d')?.drawImage(video.current,0,0);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(blob)keep(new File([blob],'live-catch.jpg',{type:'image/jpeg'}),'photo')}
 function startVideo(){if(!stream.current)return;const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp8,opus')?'video/webm;codecs=vp8,opus':'video/webm';const chunks:Blob[]=[];const item=new MediaRecorder(stream.current,{mimeType:mime});recorder.current=item;item.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};item.onstop=()=>{setRecording(false);const blob=new Blob(chunks,{type:'video/webm'});keep(new File([blob],'live-catch.webm',{type:'video/webm'}),'video')};item.start(250);setRecording(true);timer.current=setTimeout(()=>item.state==='recording'&&item.stop(),15000)}
 function stopVideo(){if(recorder.current?.state==='recording')recorder.current.stop();if(timer.current)clearTimeout(timer.current)}
 async function publish(){if(!session||!captured)return;setBusy(true);setError('');try{const signed=await post(`/catches/capture-sessions/${session.id}/media/presign`,{content_type:captured.file.type,size:captured.file.size,role:'evidence'});const upload=await fetch(signed.upload_url,{method:'PUT',body:captured.file,credentials:signed.upload_url.startsWith('/')?'include':'omit',headers:{...signed.headers,...(signed.upload_url.startsWith('/')?{'X-CSRF-Token':csrf()}: {})}});if(!upload.ok)throw new Error('The live media upload failed.');await post(`/catches/capture-sessions/${session.id}/media/${signed.id}/complete`);setResult(await post(`/catches/capture-sessions/${session.id}/finalize`,{category,description,address}));stream.current?.getTracks().forEach(track=>track.stop());}catch(caught:any){setError(caught.message)}finally{setBusy(false)}}
 if(me?.identity_type!=='registered'||!me?.handle)return <div className="state"><Lock/><h2>Public profile required</h2><p>Link Google and create an opted-in public handle before starting a Civic Catch.</p><Link className="button dark" href="/profile">Open Profile</Link></div>;
 if(result)return <div className="success-panel"><ShieldCheck size={54}/><h1>Catch received</h1><p>{result.visibility==='public'?'It passed the configured checks and is visible on your profile.':'It remains private while required safety checks are incomplete.'} Civic Catches award 0 XP.</p><Link className="button dark" href={`/profile/${me.handle}`}>View profile journal</Link></div>;
 return <><header className="page-title"><span className="kicker">LIVE CIVIC CATCH</span><h1>Record what is happening now</h1><p>Live camera and precise location are required. Gallery files cannot be selected.</p></header><div className="catch-rules"><Lock/><span>Original media stays private. Public posts show exact capture time and location. Browser freshness evidence is not cryptographic proof.</span></div><section className="live-camera-card">{!session?<button type="button" className="camera-permission" onClick={start}><Camera size={38}/><strong>Enable live camera and location</strong><span>No gallery option is provided</span></button>:<><div className="camera-stage">{captured?(captured.kind==='photo'?<img src={captured.url} alt="Captured Civic Catch"/>:<video src={captured.url} controls playsInline/>):<video ref={video} autoPlay muted playsInline/>}{captured&&<button className="discard-capture" onClick={()=>setCaptured(null)} aria-label="Discard capture"><X/></button>}</div><div className="capture-modes"><button className={mode==='photo'?'selected':''} disabled={recording} onClick={()=>setMode('photo')}><Camera/>Photo</button><button className={mode==='video'?'selected':''} disabled={recording} onClick={()=>setMode('video')}><Video/>Video · 15 sec</button></div>{!captured&&(mode==='photo'?<button className="shutter" onClick={takePhoto} aria-label="Take live photo"><span/></button>:recording?<button className="shutter recording" onClick={stopVideo} aria-label="Stop recording"><CircleStop/></button>:<button className="shutter" onClick={startVideo} aria-label="Start 15 second recording"><span/></button>)}<div className="capture-proof"><Clock size={14}/>{new Date(session.server_started_at).toLocaleString('en-IN')}<LocateFixed size={14}/>{session.location.lat.toFixed(5)}, {session.location.lng.toFixed(5)}</div></>}</section>{captured&&<section className="form-panel catch-caption"><label>Observable category<select value={category} onChange={event=>setCategory(event.target.value)}><option value="littering">Littering</option><option value="spitting">Spitting</option><option value="prohibited_smoking">Prohibited smoking</option></select></label><label>Description<textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="Describe observable behaviour without names, handles, phone numbers or personal identification." rows={4}/></label><label>Exact location label<input value={address} onChange={event=>setAddress(event.target.value)}/></label><button className="button game-cta full" disabled={busy||description.trim().length<2} onClick={publish}>{busy?'Processing private media…':'Post to my Catch wall'}</button><p className="field-note">This post earns no XP and cannot be commented on, reacted to or shared in CivicQuest V1.</p></section>}{error&&<div className="error" role="alert">{error}</div>}</>
}
