'use client';

import {useQuery} from '@tanstack/react-query';
import {Bell,Check,Leaf,Lock} from 'lucide-react';
import Link from 'next/link';
import {useEffect,useState} from 'react';

import {api,post} from '@/lib/api';

type Props={cfg:any;me:any;busy:boolean;notify:(message:string)=>void;act:(fn:()=>Promise<any>,message?:string)=>Promise<any>};

export function NotificationsScreen({cfg,me,busy,notify,act}:Props){const inbox=useQuery({queryKey:['notifications'],queryFn:()=>api('/notifications')});const preferences=useQuery({queryKey:['notification-preferences'],queryFn:()=>api('/notification-preferences')});const [settings,setSettings]=useState({report_updates:true,action_reminders:true,push:false});useEffect(()=>{if(preferences.data)setSettings(preferences.data)},[preferences.data]);async function enablePush(){try{if(me?.identity_type!=='registered')return notify('Link an account before enabling browser push.');if(!('PushManager'in window)||!cfg.push_public_key)return notify('Browser push is unavailable in this local configuration.');const permission=await Notification.requestPermission();if(permission!=='granted')return notify('Browser push remains off.');const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:cfg.push_public_key});await post('/push/subscriptions',subscription.toJSON());setSettings(value=>({...value,push:true}));notify('Browser push enabled. Save your preferences to keep it on.')}catch(error:any){notify(error.message)}}async function save(){await act(()=>api('/notification-preferences',{method:'PUT',body:JSON.stringify(settings)}),'Notification choices saved')}
 return <><header className="page-title"><span className="kicker">INBOX & REMINDERS</span><h1>Your city updates</h1><p>Choose what CivicQuest may send, then follow progress from one factual inbox.</p></header><section className="notification-settings"><h2><Bell/>Preferences</h2><label><span><strong>Followed report updates</strong><small>Comments, verified status and sourced complaint changes</small></span><input type="checkbox" checked={settings.report_updates} onChange={event=>setSettings({...settings,report_updates:event.target.checked})}/></label><label><span><strong>Civic Action reminders</strong><small>Joined event timing and proof decisions</small></span><input type="checkbox" checked={settings.action_reminders} onChange={event=>setSettings({...settings,action_reminders:event.target.checked})}/></label><label><span><strong>Browser push</strong><small>{me?.identity_type==='registered'?'Optional device alerts':'A linked account is required'}</small></span><input type="checkbox" checked={settings.push} disabled={me?.identity_type!=='registered'} onChange={event=>event.target.checked?enablePush():setSettings({...settings,push:false})}/></label><button className="button dark full" disabled={busy} onClick={save}><Check/>Save choices</button>{!cfg.push_public_key&&<p className="field-note"><Lock/>Push delivery is not configured in local demo mode. Inbox preferences still work.</p>}</section><section className="notification-inbox">{inbox.data?.items?.map((item:any)=><article className={item.read?'read':''} key={item.id}><span><Leaf/></span><Link href={item.href} onClick={()=>act(()=>post(`/notifications/${item.id}/read`),'Update opened')}><h2>{item.title}</h2><p>{item.body}</p><small>{new Date(item.created_at).toLocaleString('en-IN')}</small></Link>{!item.read&&<i/>}</article>)}{!inbox.isPending&&!inbox.data?.items?.length&&<div className="state"><Bell/><h2>All quiet for now</h2><p>Follow a report or join an Action to receive meaningful updates.</p></div>}</section></>}
