'use client';

import {useQuery} from '@tanstack/react-query';
import {ArrowRight,Bell,Camera,Check,Compass,Flag,LogOut,Settings,Share2,ShieldCheck,Sparkles,Trophy} from 'lucide-react';
import Link from 'next/link';
import {useState} from 'react';

import {api,post,pretty} from '@/lib/api';
import {CharacterPortrait} from './character-portrait';

type Props={cfg:any;me:any;busy:boolean;notify:(message:string)=>void;act:(fn:()=>Promise<any>,message?:string)=>Promise<any>};
const badgeCodes=['first_verified_report','seven_day_streak','zone_scout','high_impact_helper','first_verified_action','neighbourhood_hero','early_bird','level_10','first_assist','ward_champion','high_severity_fix','century_club'];
function GoogleMark(){return <svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20"><path fill="#4285F4" d="M21.6 12.23c0-.71-.06-1.4-.18-2.06H12v3.9h5.38a4.6 4.6 0 0 1-2 3.02v2.53h3.24c1.9-1.75 2.98-4.33 2.98-7.39Z"/><path fill="#34A853" d="M12 22c2.7 0 4.98-.9 6.63-2.38l-3.24-2.53c-.9.6-2.05.96-3.39.96-2.61 0-4.82-1.76-5.61-4.13H3.04v2.61A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.39 13.92A6 6 0 0 1 6.08 12c0-.67.12-1.32.31-1.92V7.47H3.04A10 10 0 0 0 2 12c0 1.61.39 3.14 1.04 4.53l3.35-2.61Z"/><path fill="#EA4335" d="M12 5.95c1.47 0 2.78.5 3.82 1.49l2.87-2.87A9.62 9.62 0 0 0 12 2a10 10 0 0 0-8.96 5.47l3.35 2.61C7.18 7.71 9.39 5.95 12 5.95Z"/></svg>}

export function ProfileScreen({cfg,me,busy,notify,act}:Props){
 const reports=useQuery({queryKey:['my-reports'],queryFn:()=>api('/me/reports')});const ledger=useQuery({queryKey:['ledger'],queryFn:()=>api('/users/me/xp-events')});const [handle,setHandle]=useState(me?.handle||'');const [name,setName]=useState(me?.display_name||'');const [card,setCard]=useState<string>();
 async function demo(persona:string){const value=await act(()=>post(`/auth/demo/${persona}`),`Using ${pretty(persona)} demo identity`);if(value)location.reload()}
 async function google(){if(!cfg.google?.enabled&&!cfg.google_enabled){notify(`Google sign-in needs OAuth credentials. Add them to .env and register ${cfg.google?.callback_url||location.origin+'/api/v1/auth/google/callback'} in Google Cloud.`);return}const result=await act(()=>post('/auth/link/google'),'Opening Google');if(result)location.assign(result.url)}
 async function createCard(){const made=await act(()=>post('/share-cards',{kind:'civic_card'},crypto.randomUUID()),'Preparing your Civic Card');if(!made)return;for(let attempt=0;attempt<15;attempt++){await new Promise(resolve=>setTimeout(resolve,700));const state=await api(`/share-cards/${made.id}`);if(state.state==='ready'){setCard(state.url);return}}notify('The card is still processing. It will be available shortly.')}
 async function shareCard(){
  if(!card)return;const url=new URL(card,location.origin).href;
  if(navigator.share)await navigator.share({title:'My CivicQuest Civic Card',url});
  else{await navigator.clipboard.writeText(url);notify('Civic Card link copied')}
 }
 const levelStart=me?.level_start_xp||0,next=me?.next_level_xp||100,progress=Math.max(0,Math.min(100,((me?.xp||0)-levelStart)/(next-levelStart)*100));
 return <><section className="my-civic-card"><div className="my-card-top"><CharacterPortrait id={me?.portrait_id} name={me?.display_name}/><div><span className="kicker">MY CIVIC CARD</span><h1>{me?.display_name||'Mumbai Explorer'}</h1><p>{me?.handle?`@${me.handle}`:'Private guest progress'}</p></div><strong>{me?.xp||0}<small>XP</small></strong></div><div className="level-progress"><span>Level {me?.level||1}</span><span>{next-(me?.xp||0)} XP to next level</span><i><b style={{width:`${progress}%`}}/></i></div></section><div className="profile-public-stats"><span><strong>{me?.verified_reports||0}</strong>verified</span><span><strong>{me?.resolved_reports||0}</strong>resolved</span><span><strong>{me?.streak||0}</strong>day streak</span></div>
 <div className="profile-quick-links"><Link href="/quests"><Flag/>Quest Log<ArrowRight/></Link>{me?.handle&&<Link href={`/profile/${me.handle}`}><Compass/>Public profile<ArrowRight/></Link>}<Link href="/notifications"><Bell/>Notifications<ArrowRight/></Link>{['moderator','admin'].includes(me?.role)&&<Link href="/admin"><ShieldCheck/>Review workspace<ArrowRight/></Link>}</div>
 <section className="report-section identity-panel"><h2><Sparkles/>Choose your character <small>Optional</small></h2><p>Simple portraits give your Civic Card a game identity. They never appear on the civic map.</p><div className="portrait-strip">{[{id:null,name:'Initials'},...(cfg.portraits||[])].map((portrait:any)=><button aria-label={portrait.name} aria-pressed={(me?.portrait_id||null)===portrait.id} className={(me?.portrait_id||null)===portrait.id?'selected':''} key={portrait.id||'initials'} disabled={busy} onClick={()=>act(()=>api('/profiles/me/portrait',{method:'PUT',body:JSON.stringify({portrait_id:portrait.id})}),'Character saved')}><CharacterPortrait id={portrait.id} name={me?.display_name}/><span>{portrait.name}</span></button>)}</div>
 <div className="google-account-panel"><GoogleMark/><div><strong>{me?.linked_providers?.includes('google')?'Google account connected':me?.identity_type==='guest'?'Save progress with Google':'Connect your Google account'}</strong><p>{me?.linked_providers?.includes('google')?'Your civic identity can be used across devices.':'Verification, comments, Actions and public profiles require a linked account.'}</p></div>{me?.linked_providers?.includes('google')?<span className="google-connected"><Check/>Connected</span>:<button className="button google-button" disabled={busy} onClick={google}>{me?.identity_type==='guest'?'Continue with Google':'Connect Google'}</button>}</div>
 {!cfg.google?.enabled&&!cfg.google_enabled&&!me?.linked_providers?.includes('google')&&<p className="field-note google-setup-note">Google OAuth is not configured on this local server. The option remains visible; add <code>CQ_GOOGLE_CLIENT_ID</code> and <code>CQ_GOOGLE_CLIENT_SECRET</code> to enable it.</p>}
 {me?.identity_type==='registered'&&<div className="profile-form"><label>Public handle<input value={handle} onChange={event=>setHandle(event.target.value)} placeholder="mumbai_helper"/></label><label>Display name<input value={name} onChange={event=>setName(event.target.value)}/></label><button className="button dark full" disabled={busy||handle.length<3||name.length<2} onClick={()=>act(()=>post('/profiles/me/handle',{handle,display_name:name}),'Public profile saved')}>Save public identity</button></div>}</section>
 {me?.identity_type==='registered'&&<section className="catch-journal-entry"><Camera/><div><span className="kicker">LIVE PROFILE JOURNAL</span><h2>Civic Catch</h2><p>Record a live photo or a 15-second video. Catch posts earn no XP and stay outside the map and feed.</p></div><Link className="button light" href="/profile/catches/new">Open camera</Link></section>}
 <section className="report-section"><h2><Trophy/>Twelve V1 badges</h2><div className="twelve-badges">{badgeCodes.map(code=><div className={(me?.badges||[]).includes(code)?'earned':''} key={code}><Trophy/><span>{pretty(code)}</span></div>)}</div></section>
 <section className="report-section"><div className="profile-section-head"><h2><Flag/>My reports</h2><Link href="/capture">Add report</Link></div>{reports.data?.items?.slice(0,5).map((item:any)=><Link className="profile-report-row" href={`/i/${item.public_code}`} key={item.id}><span className={`severity-pill ${item.severity}`}>{item.severity}</span><span><strong>{item.title}</strong><small>{item.public_code} · {pretty(item.status)}</small></span><ArrowRight/></Link>)}{!reports.isPending&&!reports.data?.items?.length&&<p className="empty-copy">Your submitted reports will appear here.</p>}</section>
 <section className="report-section"><h2><Share2/>Share verified impact</h2><p>Generate a downloadable Civic Card from public, verified records.</p><button className="button dark full" disabled={busy||!me?.handle} onClick={createCard}>Create Civic Card</button>{card&&<><img className="share-preview" src={card} alt="Generated Civic Card"/><div className="button-row"><a className="button outline" href={card} download="civicquest-card.png">Download</a><button className="button outline" onClick={shareCard}>Share</button></div></>}</section>
 {ledger.data?.items?.length>0&&<details className="report-section"><summary>XP history</summary>{ledger.data.items.slice(0,10).map((item:any)=><div className="profile-report-row" key={item.id}><span>{pretty(item.event_type)}</span><strong>{item.points>0?'+':''}{item.points}</strong></div>)}</details>}
 {cfg.demo_mode&&<section className="demo-profile-switch"><span className="kicker">LOCAL DEMO IDENTITIES</span><p>These synthetic profiles are available only in local/test mode.</p><div>{['maya','arjun','moderator','admin'].map(persona=><button className="button outline" disabled={busy} key={persona} onClick={()=>demo(persona)}>{pretty(persona)}</button>)}</div></section>}
 <button className="profile-logout" onClick={async()=>{await post('/auth/logout');location.assign('/')}}><LogOut/>End this browser session</button><p className="profile-settings"><Settings/>Account deletion and session controls are available through the identity API.</p></>;
}
