'use client';

import {useQuery} from '@tanstack/react-query';
import {ArrowLeft, Bell, Check, Download, Eye, Flag, MapPin, MessageCircle, Send, Share2, ShieldCheck, Sparkles} from 'lucide-react';
import Link from 'next/link';
import {useMemo, useState} from 'react';
import {api, post, pretty} from '@/lib/api';

type Props={id:string;initial?:any;me:any;busy:boolean;notify:(message:string)=>void;act:(fn:()=>Promise<any>,message?:string)=>Promise<any>};
function DateTime({value}:{value:string}){return <>{new Date(value).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</>}

export function ReportDetailScreen({id,initial,me,busy,notify,act}:Props){
 const query=useQuery({queryKey:['report',id],queryFn:()=>api(`/reports/${id}`),initialData:initial});
 const comments=useQuery({queryKey:['comments',id],queryFn:()=>api(`/reports/${id}/comments`),enabled:Boolean(query.data?.visibility==='public')});
 const [body,setBody]=useState('');const [concern,setConcern]=useState('');const [showConcern,setShowConcern]=useState(false);const [commentConcern,setCommentConcern]=useState<string>();const [commentReason,setCommentReason]=useState('');const [shareCard,setShareCard]=useState<string>();const report=query.data;
 const timeline=useMemo(()=>{if(!report)return[];const civic=(report.timeline||[]).map((event:any)=>({label:pretty(event.action),at:event.created_at,source:'CivicQuest'}));const official=(report.escalation?.events||[]).map((event:any)=>({label:event.status,at:event.occurred_at,source:report.escalation.source_name||'Official source'}));return[...civic,...official].sort((a,b)=>new Date(a.at).getTime()-new Date(b.at).getTime())},[report]);
 if(query.isPending)return <div className="state"><Sparkles className="spin"/><p>Opening report…</p></div>;
 if(query.isError||!report)return <div className="error" role="alert">This report could not be opened.</div>;
 async function addComment(){if(me?.identity_type!=='registered')return notify('Link Google before joining the discussion.');if(body.trim().length<2)return;await act(()=>post(`/reports/${id}/comments`,{body,kind:'comment'}),'Comment published');setBody('')}
 async function createShare(kind:'resolved_fix'|'before_after'){if(me?.identity_type!=='registered'||!me?.handle)return notify('Create a linked public profile before sharing.');const made=await act(()=>post('/share-cards',{kind,report_id:report.id},crypto.randomUUID()),'Preparing a safe share card');if(!made)return;for(let attempt=0;attempt<15;attempt++){await new Promise(resolve=>setTimeout(resolve,700));const state=await api(`/share-cards/${made.id}`);if(state.state==='ready'){setShareCard(state.url);return}}notify('The share card is still processing.')}
 return <><Link className="back-link" href="/"><ArrowLeft size={16}/>Back to Explore</Link><article className="mobile-report-detail">
  <div className="detail-photo-wrap">{report.image_url?<img className="report-photo" src={report.image_url} alt={report.title}/>:<div className="photo-placeholder"><MapPin size={46}/></div>}<span className={`severity-pill ${report.severity}`}>{report.severity} severity</span></div>
  <header className="detail-title"><span className="kicker">{report.public_code}</span><h1>{report.title}</h1><p><MapPin size={15}/>{report.address}</p><div className="report-state-line"><span className={`tag ${report.status==='resolved'?'green':'orange'}`}>{pretty(report.status)}</span><span>{pretty(report.verification)}</span></div></header>
  <p className="description">{report.description||'No additional description was provided.'}</p>
  {report.pending_xp>0&&<div className="pending-reward"><Sparkles size={20}/><div><strong>{report.pending_xp} XP pending</strong><small>Verification releases the accepted severity reward</small></div></div>}
  <div className="report-primary-actions"><button className={report.seen?'selected':''} disabled={busy} onClick={()=>act(()=>report.seen?api(`/reports/${id}/seen`,{method:'DELETE'}):post(`/reports/${id}/seen`),report.seen?'Seen confirmation removed':'Thanks for confirming what you saw')}><Eye size={19}/><strong>{report.seen?'Seen':"I've Seen This"}</strong><span>{report.seen_count||0}</span></button><button className={report.following?'selected':''} disabled={busy} onClick={()=>me?.identity_type==='registered'?act(()=>report.following?api(`/reports/${id}/follow`,{method:'DELETE'}):post(`/reports/${id}/follow`),report.following?'Report unfollowed':'You will receive meaningful updates'):notify('Link Google to follow reports.')}><Bell size={19}/><strong>{report.following?'Following':'Follow'}</strong></button></div>
  <p className="field-note">Seen is a reversible community attention signal. It awards no XP and does not verify this report.</p>
  {report.escalation&&<section className="complaint-card"><span className="kicker">ACCOUNTABILITY STATUS</span><h2>{report.escalation.official_id?`Official complaint ${report.escalation.official_id}`:report.escalation.state==='handed_off'?'Official complaint pending':'Community threshold reached'}</h2><p>{report.escalation.state==='review'?'A CivicQuest moderator is reviewing the evidence. Nothing is sent automatically.':report.escalation.state==='approved'?'The case is approved for a moderator-operated handoff.':report.escalation.state==='handed_off'?`Handed to ${report.escalation.source_name}.`:'This escalation case was reviewed.'}</p>{report.escalation.source_url&&<a href={report.escalation.source_url} target="_blank" rel="noreferrer">View official source</a>}</section>}
  <section className="report-section"><h2>Progress</h2><ol className="timeline">{timeline.map((event:any,index:number)=><li key={`${event.at}-${index}`}><span/><div><strong>{event.label}</strong><small>{event.source} · <DateTime value={event.at}/></small></div></li>)}</ol>{!timeline.length&&<p>No completed milestones yet.</p>}</section>
  {report.status==='resolved'&&<section className="report-section"><h2><Share2/>Share this verified fix</h2><p>Cards use public safe data and stop working if the report is restricted.</p><div className="button-row"><button className="button dark" disabled={busy} onClick={()=>createShare('resolved_fix')}>Resolved fix</button><button className="button outline" disabled={busy} onClick={()=>createShare('before_after')}>Before / after story</button></div>{shareCard&&<><img className="share-preview" src={shareCard} alt="Generated verified resolution card"/><a className="button outline full" download="civicquest-resolution.png" href={shareCard}><Download/>Download</a></>}</section>}
  {report.can_verify&&<section className="report-section"><h2><ShieldCheck size={20}/>Independent verification</h2><p>Confirm only after checking this place. The reporter cannot verify their own report.</p><div className="button-row"><button className="button dark" disabled={busy} onClick={()=>act(()=>post(`/reports/${id}/verify`,{result:'confirmed'}),'Verification recorded')}><Check size={16}/>Still here</button><button className="button outline" disabled={busy} onClick={()=>act(()=>post(`/reports/${id}/verify`,{result:'disputed'}),'Sent to moderation')}>Something changed</button></div></section>}
  <section className="report-section discussion"><h2><MessageCircle size={20}/>Community discussion</h2><p>Keep comments factual and free of personal contact information. Comments earn no XP.</p>{comments.data?.items?.map((item:any)=><article key={item.id}><div className="comment-head"><strong>{item.author}</strong>{item.can_report&&<button aria-label={`Report comment by ${item.author}`} onClick={()=>{setCommentConcern(commentConcern===item.id?undefined:item.id);setCommentReason('')}}><Flag size={14}/></button>}</div><p>{item.body}</p><small><DateTime value={item.created_at}/></small>{commentConcern===item.id&&<div className="comment-concern"><label>Why should moderators review this comment?<textarea value={commentReason} onChange={event=>setCommentReason(event.target.value)} rows={2}/></label><button className="button outline" disabled={busy||commentReason.trim().length<5} onClick={async()=>{const result=await act(()=>post(`/reports/${id}/comments/${item.id}/abuse`,{reason:commentReason}),'Comment sent to moderation');if(result)setCommentConcern(undefined)}}>Submit comment concern</button></div>}</article>)}{!comments.isPending&&!comments.data?.items?.length&&<p className="empty-copy">No comments yet.</p>}<div className="comment-compose"><textarea value={body} onChange={event=>setBody(event.target.value)} placeholder={me?.identity_type==='registered'?'Add factual context…':'Link Google to comment'} disabled={me?.identity_type!=='registered'}/><button aria-label="Post comment" disabled={busy||body.trim().length<2} onClick={addComment}><Send size={18}/></button></div></section>
  <button className="text-button" onClick={()=>setShowConcern(!showConcern)}><Flag size={15}/>Report a concern</button>{showConcern&&<section className="report-section"><label>What should moderators review?<textarea value={concern} onChange={event=>setConcern(event.target.value)} rows={3}/></label><button className="button outline" disabled={busy||concern.length<5} onClick={()=>act(()=>post(`/reports/${id}/abuse`,{reason:concern}),'Concern sent to moderation')}>Submit concern</button></section>}
 </article></>
}
