include classpath("application.conf")
node-address { protocol = http, host = "*", port = 9324, context-path = "" }
rest-sqs { enabled = true, bind-port = 9324, bind-hostname = "0.0.0.0" }
messages-storage { enabled = true }
queues {
  civicquest {
    defaultVisibilityTimeout = 120 seconds
    receiveMessageWait = 10 seconds
    deadLettersQueue { name = "civicquest-dead", maxReceiveCount = 5 }
  }
  civicquest-dead { }
}
